### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by ntnmrndn**
I'm not so sure how to reproduce this, or where it comes from but we did encounter it in pairs & pairs engage. Maybe this would be safer ?

### CODE REVIEW

**Comment by muukii** [comment]
@ntnmrndn 
Thank you.
Let me also investigate this issue. Could you show me that crash log? I'd like to check the call stack and where happens nil accessing.

**Comment by ntnmrndn** [comment]
https://console.firebase.google.com/u/0/project/engage-production-59731/crashlytics/app/ios:jp.eure.engage/issues/941c98e32165c89b2c914f1637d442b1?time=last-seven-days&sessionId=a83937d808b04cf9a338d3f54620bee2_DNE_8_v2

**Comment by ntnmrndn** [comment]
https://console.firebase.google.com/u/0/project/eure.jp:api-project-301387065575/crashlytics/app/ios:jp.eure.pairs/issues/62af19547266b024afae8ba41793ce18?time=last-seven-days&sessionId=
https://console.firebase.google.com/u/0/project/eure.jp:api-project-301387065575/crashlytics/app/ios:jp.eure.pairs/issues/1140a202a2fb1cafe491679791292573?time=last-seven-days&sessionId=12c124c3ae08410f92514d6fca51bad3_DNE_8_v2

**Comment by muukii** [comment]
thanks, I attach screenshots here
image
image

**Comment by muukii** [comment]
@ntnmrndn 
Hi, 
I've created another PR to try to fix this.
Could you try it on my branch before making a release?

**Comment by ntnmrndn** [comment]
@muukii This could work too ! Maybe it would still be safer to give it a default value: See the updated PR

**Comment by ntnmrndn** [comment]
I have no way to reproduce the crash unfortunately :-(

**Comment by muukii** [comment]
@ntnmrndn 

>  Maybe it would still be safer to give it a default value: See the updated PR

I know what you mean, to be safe, it's good to use the default value.
However, I'd like to keep using the default nil value. because we don't have yet exact cause and nil means exactly meaning (not tracking scrollview)

So, If I do something to fix, I put a logger to output error logs.
And then we see that error logs in Crashlytics as non-fatal-error.
It might be stuff to fix this issue correctly.

**Comment by muukii** [comment]
@ntnmrndn 
So, Can I fix this issue without using the default value?, I mean I'd like to use my PR for this.
if this does not fix, I'll think of the next plan to fix.

**Comment by ntnmrndn** [comment]
@muukii I don't know how to reproduce, so I can't check if this is correct or not. But your explanation makes sense, so let's try it ! We'll see if the crash reports stop :)

**Pull request closed without merging**
